name: flutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  flutter_secure_storage: ^9.2.2
  flutter_web_auth_2: ^4.0.0-alpha.0
  http: ^1.2.2
  jwt_decoder: ^2.0.1
  oidc: ^0.7.0
  oidc_default_store: ^0.2.0+9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
